### ISSUE TITLE
Remove "listItem-2P_4kh" (Download Apps) button

### ISSUE THREAD

**Issue by erazemkokot** [MrTipson/DiscordCSS#2]
![Screenshot from 2020-06-16 19-42-50](https://user-images.githubusercontent.com/46302511/84808888-9ccb8800-b009-11ea-8e84-d619208fd28c.png)

![Screenshot from 2020-06-16 19-43-25](https://user-images.githubusercontent.com/46302511/84808956-b2d94880-b009-11ea-8e94-1603f23928bf.png)

**Comment by MrTipson** [comment]
Resolved in commit https://github.com/MrTipson/DiscordCSS/commit/549c5cb56ce84abb2daf1014fb3b65d229248dc9
